Transform: AWS::Serverless-2016-10-31
Resources:
  CustomEmail:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CustomEmail'
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: CustomEmail
      CodeUri: src
      Handler: epsagon.wrapper
      Runtime: python3.8
      MemorySize: !Ref 'EnvConfiglambdamemorysizeAsString'
      Timeout: !Ref 'EnvConfiglambdatimeoutAsString'
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*'
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub '/${EnvironmentTagName}/'
          EPSAGON_HANDLER: custom_email.custom_email
          EPSAGON_APP_NAME: '!Ref ${AWS::StackName}'
          EPSAGON_TOKEN: '!Ref EpsagontokenAsString'
      Events:
        EventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - custom_email
            EventBusName: !Ref 'EnvConfigeventbridgethiscoveryeventbusAsString'
          Metadata:
            StackeryName: CustomEmail
      Layers:
        - arn:aws:lambda:eu-west-1:066549572091:layer:epsagon-python-layer:325
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfiglambdamemorysizeAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/lambda/memory-size
  EnvConfiglambdatimeoutAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/lambda/timeout
  EnvConfigeventbridgethiscoveryeventbusAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/eventbridge/thiscovery-event-bus
  EpsagontokenAsString:
    Type: String
    Description: Epsagon token (GitHub secret injected by deployment script)
Metadata:
  EnvConfigParameters:
    EnvConfiglambdamemorysizeAsString: lambda.memory-size
    EnvConfiglambdatimeoutAsString: lambda.timeout
    EnvConfigeventbridgethiscoveryeventbusAsString: eventbridge.thiscovery-event-bus