name: Feature pipeline

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '4549-*'


env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EPSAGON_TOKEN: ${{ secrets.EPSAGON_TOKEN }}
  SAM_TEMPLATE: template.yaml
  AWS_REGION: eu-west-1
  STACK_NAME: thiscovery-crm


jobs:
  test:
    name: Test on AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure testing environment
        uses: THIS-Institute/actions-configure-test-env@v0.10
        with:
          afs25_account: ${{ secrets.AFS25_AWS_ACCOUNT }}
          sem86_account: ${{ secrets.SEM86_AWS_ACCOUNT }}
          amp205_account: ${{ secrets.AMP205_AWS_ACCOUNT }}

      - name: Build
        uses: ./.github/actions/build-stack

      - name: Package
        uses: ./.github/actions/package
        with:
          from_env: ${{ env.AWS_TEST_ENV }}
          to_env: ${{ env.AWS_TEST_ENV }}
          deployment_role: ${{ env.TESTING_ACCOUNT_DEPLOYMENT_ROLE }}
          artifacts_bucket: ${{ env.ARTIFACTS_BUCKET }}

      - name: Execute thiscovery deployment via cli
        run: |
          thiscovery deploy ${{ env.STACK_NAME }}

      # Currently, this step has to be done in the workflow rather than composite action due to this issue: https://github.com/actions/runner/issues/789
      - name: Assume the testing role in testing account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.TESTING_ACCOUNT_TEST_ROLE }}
          role-session-name: ${{ env.STACK_NAME }}-testing
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Run tests
        uses: ./.github/actions/run-unittests
