name: Pipeline

on:
  push:
    branches:
      - 'master'
      - '4361-github-pipeline-exploration'
  pull_request:
    branches:
      - 'master'

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EPSAGON_TOKEN: ${{ secrets.EPSAGON_TOKEN }}
  SAM_TEMPLATE: template.yaml
  TESTING_REGION: eu-west-1

  PROD_STACK_NAME: thiscovery-crm-staging
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::756495104356:role/aws-sam-cli-managed-staging-PipelineExecutionRole-1EVVZ8OZFP6UJ
  PROD_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::756495104356:role/aws-sam-cli-managed-stagi-CloudFormationExecutionR-1GVTGH3ZBWKAM
  PROD_ARTIFACTS_BUCKET: aws-sam-cli-managed-staging-pipel-artifactsbucket-1tnfw8mstb50t
  # If there are functions with "Image" PackageType in your template,
  # uncomment the line below and add "--image-repository ${PROD_IMAGE_REPOSITORY}" to
  # prod "sam package" and "sam deploy" commands.
  # PROD_IMAGE_REPOSITORY = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  PROD_REGION: eu-west-1
  PROD_ENV: staging

jobs:
  set-test-env:
    name: Configure test environment
    runs-on: ubuntu-latest
    steps:
      - name: Sets env vars for afs25
        run: |
          echo "AWS_TEST_ACCOUNT=${{ secrets.AFS25_AWS_ACCOUNT }}" >> $GITHUB_ENV
          echo "AWS_TEST_ENV=test-afs25" >> $GITHUB_ENV
        if: ${{ github.actor == 'afs25' }}

      - name: Sets env vars for sem86
        run: |
          echo "AWS_TEST_ACCOUNT=${{ secrets.SEM86_AWS_ACCOUNT }}" >> $GITHUB_ENV
        if: ${{ github.actor == 'sophiemachin' }}

      - name: Sets env vars for amp205
        run: |
          echo "AWS_TEST_ACCOUNT=${{ secrets.AMP205_AWS_ACCOUNT }}" >> $GITHUB_ENV
        if: ${{ github.actor == 'this-andy' }}

  calculate-env-variables:
    needs: [set-test-env]
    name: Calculate env variables
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "STACK_NAME=$(echo ${{ github.repository }} | awk -F "/" '{print $2}')" >> $GITHUB_ENV
          echo "TESTING_ARTIFACTS_BUCKET=thiscovery-devops-${{ env.AWS_TEST_ENV }}-deployment-artifacts" >> $GITHUB_ENV
          echo "TESTING_PIPELINE_ROLE=arn:aws:iam::${{ env.AWS_TEST_ACCOUNT }}:role/thiscovery-devops-${{ env.AWS_TEST_ENV }}-eu-west-1-PipelineExec" >> $GITHUB_ENV
          echo "TESTING_CF_ROLE=arn:aws:iam::${{ env.AWS_TEST_ACCOUNT }}:role/thiscovery-devops-${{ env.AWS_TEST_ENV }}-eu-west-1-CFExec" >> $GITHUB_ENV

  build-and-deploy-to-test-environment:
    needs: [calculate-env-variables]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_ROLE }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to testing account
        shell: bash
        run: |
          sam deploy --debug \ 
            --region ${TESTING_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --stack-name ${STACK_NAME}-${AWS_TEST_ENV} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --role-arn ${TESTING_CF_ROLE} \
            --parameter-overrides "EpsagontokenAsString=${EPSAGON_TOKEN} StackTagName=\"${STACK_NAME}\" EnvironmentTagName=\"${TESTING_ENV}\" EnvConfiglambdamemorysizeAsString=\"/${TESTING_ENV}/lambda/memory-size\" EnvConfiglambdatimeoutAsString=\"/${TESTING_ENV}/lambda/timeout\" EnvConfigeventbridgethiscoveryeventbusAsString=\"/${TESTING_ENV}/eventbridge/thiscovery-event-bus\""
